### ISSUE TITLE
NuGet publishing from Master

### ISSUE THREAD

**Issue by smudge202** [herecydev/TestAttributes#10]
Means branching a bit more / being a little careful, but I recommend publishing to nuget whenever master is updated.

For example: 

https://github.com/smudge202/compose/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+Publish

I have multiple packages in Compose currently, but will look much better once they're split out.

**Comment by smudge202** [comment]
Let me know if you want a hand on the appveyor side.

**Comment by herecydev** [comment]
Was planning it ahead, just don't want massively experimental stuff leaked out and "diluting" expectations.

**Comment by smudge202** [comment]
Don't suppose you could release an alpha/beta package to help with Compose.Remoting issues? Just include anything stable as opposed to anything polished?

**Comment by herecydev** [comment]
I am a generous god.

```PowerShell
Install-Package TestHelpers
```

**Comment by sblackler** [comment]
good man!

**Comment by herecydev** [comment]
It's basic but more will follow after sleep :)

**Comment by herecydev** [comment]
DDT in the latest package, 1.1.0
