### ISSUE TITLE
Smoke testing

### ISSUE THREAD

**Issue by herecydev** [herecydev/TestAttributes#11]
Ability to mark high priority tests that should be run first and will prematurely fail the testing if any of them fail.

**Comment by smudge202** [comment]
Not sure I agree with this; I appreciate what you're trying to achieve but ordering test runs is generally bad news.

**Comment by herecydev** [comment]
Something that is supported within xunit

**Comment by smudge202** [comment]
xunit does a number of things; doesn't mean we have to agree with them all. :shit:
