### ISSUE TITLE
CoreCLR

### ISSUE THREAD

**Issue by smudge202** [herecydev/TestAttributes#20]
Can TestHelpers be moved to a vNext project targetting dnx451 and dnxcore50 as well as any existing profiles (net45/net40/etc)

See the following Compose commits for some assistance or shout me on twitter/here:

https://github.com/smudge202/compose/commit/121c9c55149b97ed341101988a1f0e468163f27b
https://github.com/smudge202/compose/commit/d231fdc704dab183409ab140f7978128be585bcf
https://github.com/smudge202/compose/commit/a09fa07805ea86e5b3ae9db17c387809aa2b65c0

**Comment by smudge202** [comment]
You intend to mark this as back `in progress`? (T'is closed)

**Comment by herecydev** [comment]
It is closed. I've removed the in progress label not added?

**Comment by smudge202** [comment]
My bad =/
