### ISSUE TITLE
Data driven testing

### ISSUE THREAD

**Issue by herecydev** [herecydev/TestAttributes#6]
**Per [this issue](https://github.com/xunit/xunit/issues/376), data discovery may be problematic.**

Data discovery needs to be flexible for the developer, commonly you can:
* Supply inline data (an attribute for each test)
* Supply some data provider that can enumerate through the tests

**Comment by herecydev** [comment]
Thoughts for the following. Yes/No/Name changes/etc...

```C#
		//A
		[UnitTestCase]
		[WithValues(1, 2)]
		[WithValues(3, 4)]
		public void addTest(int a, int b)

		//B
		[UnitTestCase(1, 2)]
		[UnitTestCase(3, 4)]
		public void addTest(int a, int b)

		//C
		[UnitTestCase]
		public void addTest([WithValues(1, 2)]int a, [WithValues(3, 4)]int b)

		//D
		[UnitTestCase]
		[TestCaseSource(typeof(MyProvider))]
		public void addTest(int a, int b)
```

**Comment by mattridgway** [comment]
Can we get rid of the word Test?

**Comment by smudge202** [comment]
Until you start extending xunit (TestDiscoverers and such) it too doesn't use the word `Test` I think?

**Comment by mattridgway** [comment]
Is this valid?

[UnitTestCase(1)]
[UnitTestCase(2)]
public void addTest(int a, [WithValues(3, 4)]int b)

**Comment by herecydev** [comment]
Sure it is, :hankey:

**Comment by herecydev** [comment]
#16 Pull requested changes to naming based on feedback. Have left the categories as "Unit Test", "Component Test" etc for now. I feel that is a nice balance.

**Comment by smudge202** [comment]
Should the categories be plural? (Just asking...)

**Comment by herecydev** [comment]
Absolutely, added to the PR #16

**Comment by mattridgway** [comment]
Which of the original A,B,C,D options did we end up going for?

**Comment by herecydev** [comment]
A as it provides clearer options for the base attribute (Unit/Integration/etc) in the event that the user wants to skip, etc. Though others aren't ruled out yet.

**Comment by herecydev** [comment]
Initial design is complete, added [separate issue](#30) for inline.
